a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
print("Which operation to perform :", end="\n")
print("1.Addition :", end="\n")
print("2.Subtraction :", end="\n")
print("3.Multiplication :", end="\n")
print("4.Division :", end="\n")
print("5.Modulo :", end="\n")
print("6.Floor division :", end="\n")
print("7.Exponential :", end="\n")
c = int(input("Enter the number of operation to perform"))
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a % b)
print(a // b)
print(a ** b)
