string = "gourove roy"

print(len(string))
print(string.capitalize())
print(string.upper())
print(string.lower())
print(string.swapcase())
print(string.title())
print(string.replace("g", "G"))
print(string.count("o"))
print(string.find("o"))
print(string.index("o"))
print(string.isalnum())
print(string.isalpha())
print(string.isdecimal())
print(string.isdigit())
print(string.isidentifier())
print(string.islower())
print(string.isnumeric())
print(string.isprintable())
print(string.isspace())
print(string.istitle())
print(string.isupper())
print(string.split())
print(" ".join(["gourove", "roy"]))