songLibraries = {
    "taki": "https://www.youtube.com/watch?v=ixkoVwKQaJg&pp=ygUJdGFraSB0YWtp",
    "despacito": "https://www.youtube.com/watch?v=kJQP7kiw5Fk&pp=ygUJZGVzcGFjaXRv",
    "dream": "https://www.youtube.com/watch?v=89dGC8de0CA&pp=ygUIZHJlYW0gb24%3D",
    "shape_of_you": "https://www.youtube.com/watch?v=JGwWNGJdvx8&pp=ygUMc2hhcGUgb2YgeW91",
    "uptown_funk": "https://www.youtube.com/watch?v=OPf0YbXqDm0&pp=ygUMdXB0b3duIGZ1bmsg",
    "blinding_lights": "https://www.youtube.com/watch?v=4NRXx6U8ABQ&pp=ygUMYmxpbmRpbmcgbGlnaHRz",
    "bad_guy": "https://www.youtube.com/watch?v=DyDfgMOUjCI&pp=ygUHYmFkIGd1eQ%3D%3D",
    "senorita": "https://www.youtube.com/watch?v=Pkh8UtuejGw&pp=ygUQc2Vub3JpdGEgc29uZw%3D%3D",
    "levitating": "https://www.youtube.com/watch?v=TUVcZfQe-Kw&pp=ygUPbGV2aXRhdGluZyBzb25n",
    "someone_you_loved": "https://www.youtube.com/watch?v=zABLecsR5UE&pp=ygUSc29tZW9uZSB5b3UgbG92ZWQ%3D",
    "perfect": "https://www.youtube.com/watch?v=2Vv-BfVoq4g&pp=ygUJcGVyZmVjdCBzb25n",
    "hello": "https://www.youtube.com/watch?v=YQHsXMglC9A&pp=ygUFaGVsbG8%3D",
    "dynamite": "https://www.youtube.com/watch?v=gdZLi9oWNZg&pp=ygUHZHluYW1pdGU%3D",
    "rolling_in_the_deep": "https://www.youtube.com/watch?v=rYEDA3JcQqw&pp=ygUMcm9sbGluZyBpbiB0aGUgZGVlcA%3D%3D",
    "shallow": "https://www.youtube.com/watch?v=bo_efYhYU2A&pp=ygUJc2hhbGxvdyBzb25n",
    "roar": "https://www.youtube.com/watch?v=CevxZvSJLk8&pp=ygUFcm9hcg%3D%3D",
    "faded": "https://www.youtube.com/watch?v=60ItHLz5WEA&pp=ygUGZmFkZWQ%3D",
    "love_yourself": "https://www.youtube.com/watch?v=oyEuk8j8imI&pp=ygUMbG92ZSB5b3Vyc2VsZg%3D%3D",
    "closer": "https://www.youtube.com/watch?v=PT2_F-1esPk&pp=ygUJY2xvc2VyIHNvbmch",
    "girls_like_you": "https://www.youtube.com/watch?v=aJOTlE1K90k&pp=ygUMZ2lybHMgbGlrZSB5b3U%3D",
}
